plugins {
    id 'com.android.application'
}

android {
    namespace 'com.aistudio.corujinhafinancas.cdaccc'
    compileSdk 35

    defaultConfig {
        applicationId 'com.aistudio.corujinhafinancas.cdaccc'
        minSdk 24
        targetSdk 34
        versionCode 3
        versionName '1.0.2'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
